import json

with open('app/src/main/assets/oxford_words.json', 'r', encoding='utf-8') as f:
    words = json.load(f)

existing = {w['w'].lower().strip() for w in words}

startup_bonus = [
    {"w": "Bootstrapping", "p": "/ˈbuːtstræpɪŋ/", "t": "noun", "m": "Starting and growing a company using personal savings without outside investment.", "e": "They achieved profitability through disciplined bootstrapping rather than venture capital.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Angel Investor", "p": "/ˈeɪndʒəl ɪnˈvɛstər/", "t": "noun", "m": "A high-net-worth individual who provides early capital for a startup in exchange for equity.", "e": "An experienced angel investor gave them seed money and industry mentorship.", "c": "Startup terms", "d": "Easy"},
    {"w": "Venture Capital", "p": "/ˈvɛntʃər ˈkæpɪtəl/", "t": "noun", "m": "Financing that investors provide to startup companies believed to have long-term growth potential.", "e": "The fintech startup raised thirty million in venture capital.", "c": "Startup terms", "d": "Easy"},
    {"w": "Runway", "p": "/ˈrʌnweɪ/", "t": "noun", "m": "The amount of time a startup has until it runs out of money based on its monthly burn rate.", "e": "With new funding secured, the startup extended its runway to eighteen months.", "c": "Startup terms", "d": "Easy"},
    {"w": "Burn Rate", "p": "/bɜːrn reɪt/", "t": "noun", "m": "The rate at which a new company spends its venture capital before generating positive cash flow.", "e": "The CEO monitored the monthly burn rate to avoid premature capital crunches.", "c": "Startup terms", "d": "Easy"},
    {"w": "Churn", "p": "/tʃɜːrn/", "t": "noun/verb", "m": "The percentage of customers who stop subscribing to or using a product over a given period.", "e": "Improving customer onboarding reduced annual churn to under five percent.", "c": "Startup terms", "d": "Easy"},
    {"w": "Pitch Deck", "p": "/pɪtʃ dɛk/", "t": "noun", "m": "A concise slide presentation giving prospective investors an overview of a startup's vision and business model.", "e": "She refined the ten-slide pitch deck before meeting Silicon Valley partners.", "c": "Startup terms", "d": "Easy"},
    {"w": "Unicorn", "p": "/ˈjuːnɪkɔːrn/", "t": "noun", "m": "A privately held startup company with a valuation exceeding one billion dollars.", "e": "The AI logistics company reached unicorn status within just three years.", "c": "Startup terms", "d": "Easy"},
    {"w": "Product-Market Fit", "p": "/ˈprɒdʌkt ˈmɑːrkɪt fɪt/", "t": "noun", "m": "The degree to which a product satisfies a strong, genuine market demand.", "e": "Reaching product-market fit allowed the team to pour resources into scaling ads.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Minimum Viable Product", "p": "/ˈmɪnɪməm ˈvaɪəbəl ˈprɒdʌkt/", "t": "noun", "m": "A version of a product with just enough features to be usable by early customers who provide feedback.", "e": "They launched their minimum viable product in three weeks to test demand.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Freemium", "p": "/ˈfriːmiəm/", "t": "noun/adjective", "m": "A business model offering basic web services for free while charging for premium features.", "e": "The cloud storage app used a freemium model to attract millions of initial users.", "c": "Startup terms", "d": "Easy"},
    {"w": "Customer Acquisition Cost", "p": "/ˈkʌstəmər ˌækwɪˈzɪʃən kɒst/", "t": "noun", "m": "The total sales and marketing cost required to earn a single new paying customer.", "e": "Organic word-of-mouth kept their customer acquisition cost remarkably low.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Lifetime Value", "p": "/ˈlaɪftaɪm ˈvæljuː/", "t": "noun", "m": "The projected total revenue a business expects to earn from an average customer relationship.", "e": "A healthy SaaS company maintains customer lifetime value at three times acquisition cost.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Pivot", "p": "/ˈpɪvət/", "t": "verb/noun", "m": "A fundamental shift in business strategy after discovering that the initial approach is flawed.", "e": "When photo sharing slowed, they pivoted into an enterprise messaging platform.", "c": "Startup terms", "d": "Easy"},
    {"w": "Incubator", "p": "/ˈɪŋkjʊbeɪtər/", "t": "noun", "m": "An organization that helps startups develop by offering services, workspace, and seed funding.", "e": "The university startup incubator provided free lab space and legal guidance.", "c": "Startup terms", "d": "Easy"},
    {"w": "Accelerator", "p": "/əkˈsɛləreɪtər/", "t": "noun", "m": "A fixed-term cohort program providing mentorship and capital culminating in a public demo day.", "e": "Graduating from Y Combinator's accelerator gave them immediate investor visibility.", "c": "Startup terms", "d": "Easy"},
    {"w": "Demo Day", "p": "/ˈdɛmoʊ deɪ/", "t": "noun", "m": "An event where cohort startups present their business models to rooms filled with active investors.", "e": "They prepared for weeks to give a three-minute speech on Demo Day.", "c": "Startup terms", "d": "Easy"},
    {"w": "Cap Table", "p": "/kæp ˈteɪbəl/", "t": "noun", "m": "A detailed ledger showing the percentage ownership, equity dilution, and value of shares in a startup.", "e": "The founders maintained sixty percent ownership on their official cap table.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Term Sheet", "p": "/tɜːrm ʃiːt/", "t": "noun", "m": "A non-binding agreement outlining the basic terms and conditions under which an investment will be made.", "e": "They received three competing term sheets from venture firms this morning.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Due Diligence", "p": "/djuː ˈdɪlɪdʒəns/", "t": "noun", "m": "A comprehensive appraisal of a business undertaken by a prospective buyer or investor.", "e": "The VC completed four weeks of legal due diligence before wiring the funds.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Valuation", "p": "/ˌvæljuˈeɪʃən/", "t": "noun", "m": "The estimated financial worth of a company determined during an investment round.", "e": "The Series A round was closed at a fifty million dollar pre-money valuation.", "c": "Startup terms", "d": "Easy"},
    {"w": "Convertible Note", "p": "/kənˈvɜːrtəbəl noʊt/", "t": "noun", "m": "A form of short-term debt that converts into equity, typically in conjunction with a future financing round.", "e": "The seed investors funded the company through a convertible note with a valuation cap.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "SAFE Agreement", "p": "/seɪf əˈɡriːmənt/", "t": "noun", "m": "Simple Agreement for Future Equity; a popular contract giving investors future equity without debt.", "e": "Early backers invested two hundred thousand dollars using standard YC SAFEs.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Vesting", "p": "/ˈvɛstɪŋ/", "t": "noun", "m": "The process by which an employee accrues non-forfeitable rights to employer stock or options over time.", "e": "Their employee equity followed standard four-year vesting with a one-year cliff.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Cliff", "p": "/klɪf/", "t": "noun", "m": "A predetermined threshold period before any employee stock options begin vesting.", "e": "If an employee leaves before the one-year cliff, they receive no equity shares.", "c": "Startup terms", "d": "Easy"},
    {"w": "Disruptive Innovation", "p": "/dɪsˈrʌptɪv ˌɪnəˈveɪʃən/", "t": "noun", "m": "An innovation that significantly alters the way that consumers, industries, or businesses operate.", "e": "Streaming movies directly over high-speed internet was a classic disruptive innovation.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "First Mover", "p": "/fɜːrst ˈmuːvər/", "t": "noun", "m": "A company that gains a competitive advantage by being the first to bring a new product to market.", "e": "They enjoyed first mover advantage and secured major enterprise contracts quickly.", "c": "Startup terms", "d": "Easy"},
    {"w": "Moat", "p": "/moʊt/", "t": "noun", "m": "A business's competitive advantage that protects it from competitors and secures profit margins.", "e": "Patents and strong network effects created an impenetrable economic moat.", "c": "Startup terms", "d": "Easy"},
    {"w": "Network Effects", "p": "/ˈnɛtwɜːrk ɪˈfɛkts/", "t": "noun", "m": "The phenomenon whereby increased numbers of people or participants improve the value of a good.", "e": "Social messaging apps thrive on compounding network effects.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Scalability", "p": "/ˌskeɪləˈbɪlɪti/", "t": "noun", "m": "The capacity of a system or business to handle growing amounts of work or sales smoothly.", "e": "Software companies boast high scalability because serving new users costs almost nothing.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Traction", "p": "/ˈtrækʃən/", "t": "noun", "m": "Measurable evidence of customer interest, user engagement, and growing revenue.", "e": "Doubling active weekly users provided convincing traction for Series A.", "c": "Startup terms", "d": "Easy"},
    {"w": "User Retention", "p": "/ˈjuːzər rɪˈtɛnʃən/", "t": "noun", "m": "The ability of a company or product to keep its customers returning over time.", "e": "High day-thirty user retention demonstrated that the app fulfilled a daily habit.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Viral Loop", "p": "/ˈvaɪrəl luːp/", "t": "noun", "m": "A product design mechanism where each new user naturally invites or introduces additional users.", "e": "Referral reward credits created a self-sustaining viral loop.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Growth Hacking", "p": "/ɡroʊθ ˈhækɪŋ/", "t": "noun", "m": "A process of rapid experimentation across marketing funnels and product development for growth.", "e": "The startup used creative growth hacking to gain their first fifty thousand users.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Agile Sprint", "p": "/ˈædʒaɪl sprɪnt/", "t": "noun", "m": "A short, time-boxed period when a scrum team works to complete a set amount of product work.", "e": "The engineering team planned their two-week agile sprint on Monday.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Scrum Master", "p": "/skrʌm ˈmæstər/", "t": "noun", "m": "The facilitator for an agile development team responsible for managing project workflows.", "e": "The scrum master removed blocking tickets so the developers could ship on time.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Kanban", "p": "/ˈkænbæn/", "t": "noun", "m": "A visual system for managing work as it moves through a process using cards on boards.", "e": "They tracked user bug fixes using a digital Kanban board.", "c": "Startup terms", "d": "Easy"},
    {"w": "Tech Stack", "p": "/tɛk stæk/", "t": "noun", "m": "The combination of programming languages, tools, frameworks, and databases used in an app.", "e": "Their modern tech stack consisted of Kotlin, Jetpack Compose, and Go.", "c": "Startup terms", "d": "Easy"},
    {"w": "SaaS", "p": "/sæs/", "t": "noun", "m": "Software as a Service; a software licensing and delivery model using cloud subscriptions.", "e": "The B2B SaaS company charged forty dollars per seat every month.", "c": "Startup terms", "d": "Easy"},
    {"w": "B2B", "p": "/ˌbiː.tuːˈbiː/", "t": "adjective", "m": "Business-to-Business; commercial transactions between businesses rather than direct consumers.", "e": "They sell enterprise payroll security as a specialized B2B provider.", "c": "Startup terms", "d": "Easy"},
    {"w": "B2C", "p": "/ˌbiː.tuːˈsiː/", "t": "adjective", "m": "Business-to-Consumer; selling products directly to individual end consumers.", "e": "Mobile gaming and fitness apps are predominantly B2C businesses.", "c": "Startup terms", "d": "Easy"},
    {"w": "Seed Round", "p": "/siːd raʊnd/", "t": "noun", "m": "The first official equity funding stage raised by an early-stage startup.", "e": "They closed a two million dollar seed round to hire their initial engineering crew.", "c": "Startup terms", "d": "Easy"},
    {"w": "Series A", "p": "/ˈsɪəriːz eɪ/", "t": "noun", "m": "The first significant round of venture capital financing after proving product-market fit.", "e": "Series A financing allowed them to build out a dedicated sales department.", "c": "Startup terms", "d": "Easy"},
    {"w": "Exit Strategy", "p": "/ˈɛɡzɪt ˈstrætədʒi/", "t": "noun", "m": "A founder or investor's plan to liquidate their stake in a company through an acquisition or IPO.", "e": "Their preferred exit strategy was an acquisition by a larger tech conglomerate.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "IPO", "p": "/ˌaɪ.piːˈoʊ/", "t": "noun", "m": "Initial Public Offering; the process of offering shares of a private corporation to the public.", "e": "Trading shares surged on the morning of their widely anticipated IPO.", "c": "Startup terms", "d": "Easy"},
    {"w": "Decacorn", "p": "/ˈdɛkəkɔːrn/", "t": "noun", "m": "A private startup company whose valuation has reached ten billion dollars or higher.", "e": "With their latest round, the AI startup officially joined the ranks of global decacorns.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Gamification", "p": "/ˌɡeɪmɪfɪˈkeɪʃən/", "t": "noun", "m": "The application of typical game mechanics to other areas of activity like apps or education.", "e": "Adding daily streaks and achievement badges is effective app gamification.", "c": "Startup terms", "d": "Intermediate"},
    {"w": "Onboarding", "p": "/ˈɒnbɔːrdɪŋ/", "t": "noun", "m": "The process of introducing a new user to a product or a new employee to a team.", "e": "A clean four-screen onboarding tutorial helped new users understand core features.", "c": "Startup terms", "d": "Easy"},
    {"w": "Wireframe", "p": "/ˈwaɪərfreɪm/", "t": "noun", "m": "A visual guide and basic skeleton that represents the skeletal framework of an app or website.", "e": "The product designer sketched wireframes before building high-fidelity Figma mockups.", "c": "Startup terms", "d": "Easy"},
    {"w": "A/B Testing", "p": "/eɪ biː ˈtɛstɪŋ/", "t": "noun", "m": "Comparing two versions of a webpage or app against each other to determine which performs better.", "e": "A/B testing the sign-up button color boosted conversions by twelve percent.", "c": "Startup terms", "d": "Easy"}
]

doctor_bonus = [
    {"w": "Stethoscope", "p": "/ˈstɛθəskoʊp/", "t": "noun", "m": "A medical instrument used by doctors to listen to internal sounds of the heart and lungs.", "e": "The physician placed the stethoscope against his chest and listened to heart rhythms.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Anesthesia", "p": "/ˌænəsˈθiːziə/", "t": "noun", "m": "Insensitivity to pain, especially as artificially induced by drugs before surgical operations.", "e": "The patient drifted peacefully into sleep after the anesthesia was administered.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Biopsy", "p": "/ˈbaɪɒpsi/", "t": "noun", "m": "An examination of tissue removed from a living body to discover the presence or cause of a disease.", "e": "The dermatologist performed a minor skin biopsy to rule out malignancy.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Radiology", "p": "/ˌreɪdiˈɒlədʒi/", "t": "noun", "m": "The science dealing with X-rays, MRI scans, and other high-energy radiation for diagnosis.", "e": "The radiology department analyzed the CT scans to check for fractures.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Cardiology", "p": "/ˌkɑːrdiˈɒlədʒi/", "t": "noun", "m": "The medical branch that deals with diseases and abnormalities of the heart and blood vessels.", "e": "He was referred to cardiology for an evaluation of his irregular pulse.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Neurology", "p": "/njʊˈrɒlədʒi/", "t": "noun", "m": "The branch of medicine concerned with the diagnosis and treatment of nervous system disorders.", "e": "The neurology specialist ordered an EEG to monitor brain wave activity.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Oncology", "p": "/ɒŋˈkɒlədʒi/", "t": "noun", "m": "The study and clinical treatment of tumors and cancer.", "e": "Advances in oncology have led to targeted immunotherapies with fewer side effects.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Pediatrics", "p": "/ˌpiːdiˈætrɪks/", "t": "noun", "m": "The branch of medical care dealing with the health and diseases of infants, children, and adolescents.", "e": "She chose pediatrics because she was passionate about childhood wellness.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Dermatology", "p": "/ˌdɜːrməˈtɒlədʒi/", "t": "noun", "m": "The branch of medicine concerned with the diagnosis and treatment of skin disorders.", "e": "A routine visit to dermatology caught the suspicious sun spot early.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Orthopedics", "p": "/ˌɔːrθəˈpiːdɪks/", "t": "noun", "m": "The medical specialty dealing with the correction of deformities or injuries of the bones and joints.", "e": "After dislocating his shoulder, he had surgery performed by orthopedics.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Pathology", "p": "/pəˈθɒlədʒi/", "t": "noun", "m": "The medical science of the causes and effects of diseases through laboratory tissue analysis.", "e": "The pathology lab confirmed that the sampled lymph node was non-cancerous.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Prognosis", "p": "/prɒɡˈnoʊsɪs/", "t": "noun", "m": "The likely course and forecast of a medical condition or disease recovery.", "e": "With early detection, the patient's long-term medical prognosis was excellent.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Scalpel", "p": "/ˈskælpəl/", "t": "noun", "m": "A small and extremely sharp bladed surgical instrument used in precision operations.", "e": "The lead surgeon called for a clean scalpel and made the initial incision.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Intravenous", "p": "/ˌɪntrəˈviːnəs/", "t": "adjective", "m": "Administered or entering directly into a vein.", "e": "The nurse connected an intravenous fluid drip to restore hydration.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Catheter", "p": "/ˈkæθɪtər/", "t": "noun", "m": "A flexible medical tube inserted into the body to remove fluids or deliver medication.", "e": "The surgeon threaded a thin cardiac catheter through the artery to the heart.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Endoscopy", "p": "/ɛnˈdɒskəpi/", "t": "noun", "m": "An examination of the interior of a canal or hollow organ with an optical instrument.", "e": "An upper endoscopy revealed minor acid-induced inflammation in the stomach.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Ultrasound", "p": "/ˈʌltrəsaʊnd/", "t": "noun", "m": "Sound or other vibrations having an ultrasonic frequency, used in medical scanning.", "e": "The technician applied cooling gel before beginning the abdominal ultrasound.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Dialysis", "p": "/daɪˈæləsɪs/", "t": "noun", "m": "The clinical purification of blood by dialysis, as a substitute for normal kidney function.", "e": "The patient visited the medical clinic three mornings a week for dialysis treatments.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Resuscitation", "p": "/rɪˌsʌsɪˈteɪʃən/", "t": "noun", "m": "The action or process of reviving someone from unconsciousness or apparent death.", "e": "The emergency team initiated cardiopulmonary resuscitation immediately upon arrival.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Defibrillator", "p": "/diːˈfɪbrɪleɪtər/", "t": "noun", "m": "An apparatus used to control heart fibrillation by application of an electric shock to the chest.", "e": "The automated external defibrillator instructed responders to stand clear before delivering a shock.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Syringe", "p": "/sɪˈrɪndʒ/", "t": "noun", "m": "A tube with a nozzle and piston for sucking in and ejecting liquid in a thin stream.", "e": "The pharmacist carefully filled the sterile syringe with the prescribed vaccine dose.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Hematology", "p": "/ˌhiːməˈtɒlədʒi/", "t": "noun", "m": "The branch of medicine concerned with the study of the cause, prognosis, and treatment of blood diseases.", "e": "The hematology report showed normal hemoglobin and white blood cell levels.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Obstetrics", "p": "/əbˈstɛtrɪks/", "t": "noun", "m": "The branch of medicine and surgery concerned with childbirth and the care of women giving birth.", "e": "The obstetrics team successfully delivered twins in the labor ward this morning.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Gynecology", "p": "/ˌɡaɪnɪˈkɒlədʒi/", "t": "noun", "m": "The branch of physiology and medicine that deals with the functions and diseases of women's reproductive health.", "e": "Routine annual screenings are conducted by specialists in gynecology.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Psychiatry", "p": "/saɪˈkaɪətri/", "t": "noun", "m": "The medical specialty devoted to the diagnosis, prevention, and treatment of mental health conditions.", "e": "Clinical psychiatry combines behavioral therapy with targeted pharmacology.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Pharmacology", "p": "/ˌfɑːrməˈkɒlədʒi/", "t": "noun", "m": "The branch of medicine concerned with the uses, effects, and modes of action of drugs.", "e": "Medical students study pharmacology to understand how compounds alter cell signaling.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Incision", "p": "/ɪnˈsɪʒən/", "t": "noun", "m": "A surgical cut made in skin or flesh during an operation.", "e": "The surgeon closed the clean four-inch incision with dissolvable sutures.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Sutures", "p": "/ˈsuːtʃərz/", "t": "noun", "m": "A stitch or row of stitches holding together the edges of a surgical wound or cut.", "e": "The laceration on his knee required twelve sterile sutures to heal properly.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Forceps", "p": "/ˈfɔːrsɛps/", "t": "noun", "m": "A pair of pincers or tweezers used in surgery or in a laboratory to hold tissue.", "e": "The doctor used delicate micro-forceps to extract the tiny shard of glass.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Autopsy", "p": "/ˈɔːtɒpsi/", "t": "noun", "m": "A post-mortem examination to discover the cause of death or the extent of disease.", "e": "The medical examiner performed an autopsy to identify the exact cause of cardiac failure.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Triage", "p": "/ˈtriːɑːʒ/", "t": "noun/verb", "m": "The assignment of degrees of urgency to wounds or illnesses to decide the order of treatment.", "e": "The emergency triage nurse prioritized patients with acute chest pain.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Prosthesis", "p": "/prɒsˈθiːsɪs/", "t": "noun", "m": "An artificial body part, such as a limb, heart valve, or breast implant.", "e": "Carbon-fiber prostheses allowed the amputee athlete to run marathon distances.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Intubation", "p": "/ˌɪntjʊˈbeɪʃən/", "t": "noun", "m": "The insertion of a flexible plastic tube into the trachea to maintain an open airway.", "e": "Emergency intubation ensured steady oxygen flow before the surgery began.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Ambulance", "p": "/ˈæmbjʊləns/", "t": "noun", "m": "A vehicle equipped for taking sick or injured people to and from hospital.", "e": "Paramedics in the ambulance administered first aid while driving through traffic.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Paramedic", "p": "/ˌpærəˈmɛdɪk/", "t": "noun", "m": "A healthcare professional trained in providing advanced emergency medical care.", "e": "The paramedic stabilized the cyclist's neck before moving him to the stretcher.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Quarantine", "p": "/ˈkwɒrəntiːn/", "t": "noun/verb", "m": "A state of isolation imposed to prevent the spread of contagious disease.", "e": "Infected passengers were placed under medical quarantine for fourteen days.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Immunotherapy", "p": "/ˌɪmjʊnoʊˈθɛrəpi/", "t": "noun", "m": "The prevention or treatment of disease with substances that stimulate the immune response.", "e": "The oncologist recommended immunotherapy to train the body's T-cells to combat the tumor.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Chemotherapy", "p": "/ˌkiːmoʊˈθɛrəpi/", "t": "noun", "m": "The treatment of disease by the use of chemical substances, especially in cancer.", "e": "The patient completed six cycles of intravenous chemotherapy with promising remission.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Electrocardiogram", "p": "/ɪˌlɛktroʊˈkɑːrdiəɡræm/", "t": "noun", "m": "A record or display of a person's electrical heartbeat activity produced by electrocardiography.", "e": "The twelve-lead electrocardiogram confirmed normal sinus heart rhythm.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Encephalogram", "p": "/ɛnˈsɛfələɡræm/", "t": "noun", "m": "An image or trace recording the electrical rhythms within the brain.", "e": "The neurologist reviewed the sleep encephalogram to detect nocturnal seizures.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Hospice", "p": "/ˈhɒspɪs/", "t": "noun", "m": "A home providing compassionate care for the sick, especially the terminally ill.", "e": "The hospice nurses focused on pain alleviation, comfort, and emotional dignity.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Inoculation", "p": "/ɪˌnɒkjʊˈleɪʃən/", "t": "noun", "m": "The act of giving a person or animal a vaccine to create immunity against a disease.", "e": "Mass pediatric inoculation eradicated smallpox from the worldwide population.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Outpatient", "p": "/ˈaʊtˌpeɪʃənt/", "t": "noun", "m": "A patient who attends a hospital for treatment without staying overnight.", "e": "Knee arthroscopy is now frequently performed as a safe outpatient procedure.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Inpatient", "p": "/ˈɪnˌpeɪʃənt/", "t": "noun", "m": "A patient who stays in a hospital while under treatment.", "e": "Severe pneumonia required five days of inpatient monitoring and oxygen support.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Physiotherapy", "p": "/ˌfɪzioʊˈθɛrəpi/", "t": "noun", "m": "The treatment of disease or injury by physical methods such as massage, heat, and exercise.", "e": "Six weeks of targeted physiotherapy restored full motion to her sprained ankle.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Prophylaxis", "p": "/ˌprɒfɪˈlæksɪs/", "t": "noun", "m": "Action taken to prevent disease, especially by specified means or against a specified disease.", "e": "Travelers took oral malaria prophylaxis prior to entering the tropical reserve.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Rheumatology", "p": "/ˌruːməˈtɒlədʒi/", "t": "noun", "m": "The medical subspecialty devoted to the diagnosis and therapy of rheumatic diseases and joint arthritis.", "e": "The rheumatology team prescribed biological medications to reduce joint swelling.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Sedative", "p": "/ˈsɛdətɪv/", "t": "noun/adjective", "m": "A drug taken for its calming, soothing, or sleep-inducing effect.", "e": "A mild oral sedative helped relieve patient anxiety before the dental extraction.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Splint", "p": "/splɪnt/", "t": "noun", "m": "A strip of rigid material used for supporting and immobilizing a broken bone.", "e": "The athletic trainer applied a padded splint to stabilize the fractured wrist.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Syndrome", "p": "/ˈsɪndroʊm/", "t": "noun", "m": "A group of symptoms which consistently occur together, or a condition characterized by a set of symptoms.", "e": "Repetitive typing without ergonomic support can trigger carpal tunnel syndrome.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Tourniquet", "p": "/ˈtʊərnɪkeɪ/", "t": "noun", "m": "A device for stopping the flow of blood through a vein or artery by compression with a cord or bandage.", "e": "The first responder applied a tourniquet to control severe arterial bleeding.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Tracheotomy", "p": "/ˌtreɪkiˈɒtəmi/", "t": "noun", "m": "An incision in the windpipe made to relieve an obstruction to breathing.", "e": "The trauma surgeon performed an emergency tracheotomy when the airway collapsed.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Vascular", "p": "/ˈvæskjʊlər/", "t": "adjective", "m": "Relating to, affecting, or consisting of a vessel or vessels, especially those which carry blood.", "e": "A specialized vascular surgeon performed bypass surgery on the blocked femoral artery.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Laparoscopy", "p": "/ˌlæpəˈrɒskəpi/", "t": "noun", "m": "A surgical procedure in which a fiber-optic instrument is inserted through the abdominal wall to view the organs.", "e": "Minimally invasive laparoscopy shortened the patient's recovery to two days.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Catheterization", "p": "/ˌkæθətəraɪˈzeɪʃən/", "t": "noun", "m": "The medical procedure of inserting a catheter into a body cavity or vessel.", "e": "Cardiac catheterization revealed ninety percent narrowing in the coronary artery.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Hemodialysis", "p": "/ˌhiːmoʊdaɪˈæləsɪs/", "t": "noun", "m": "Kidney dialysis that removes waste products and excess fluid from the blood.", "e": "Hemodialysis filtered the blood safely while the transplant donor was scheduled.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Pharmacopeia", "p": "/ˌfɑːrməkəˈpiːə/", "t": "noun", "m": "An official publication containing a list of medicinal drugs with their effects and directions for use.", "e": "Every drug dispensed in the hospital is standardized according to the national pharmacopeia.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Sphygmomanometer", "p": "/ˌsfɪɡmoʊməˈnɒmɪtər/", "t": "noun", "m": "An instrument for measuring blood pressure, typically consisting of an inflatable rubber cuff.", "e": "The nurse pumped the sphygmomanometer cuff and noted a reading of 120 over 80.", "c": "Doctor & Specialized", "d": "Hard"},
    {"w": "Ophthalmoscope", "p": "/ɒfˈθælməskoʊp/", "t": "noun", "m": "An instrument for inspecting the retina and other parts of the eye.", "e": "Using an ophthalmoscope, the optometrist inspected the optic nerve and retinal vessels.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Otoscope", "p": "/ˈoʊtəskoʊp/", "t": "noun", "m": "An instrument designed for visual examination of the eardrum and the passage of the outer ear.", "e": "The pediatrician used an otoscope to confirm an infection in the left middle ear.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Electroencephalogram", "p": "/ɪˌlɛktroʊɛnˌsɛfələɡræm/", "t": "noun", "m": "A test that detects electrical activity in your brain using small metal discs attached to your scalp.", "e": "The overnight electroencephalogram ruled out abnormal seizure patterns.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Bronchoscopy", "p": "/brɒŋˈkɒskəpi/", "t": "noun", "m": "A procedure to look directly at the airways in the lungs using a thin, lighted tube.", "e": "The pulmonologist carried out a diagnostic bronchoscopy to investigate chronic lung fluid.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Angiogram", "p": "/ˈændʒioʊɡræm/", "t": "noun", "m": "An X-ray photograph of blood or lymph vessels, made by radiography.", "e": "The emergency coronary angiogram showed normal perfusion across all main branches.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Biomedicine", "p": "/ˌbaɪoʊˈmɛdɪsɪn/", "t": "noun", "m": "A branch of medical science that applies biological and physiological principles to clinical practice.", "e": "Research in biomedicine is opening new frontiers in gene therapy and cellular repair.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Phlebotomist", "p": "/flɪˈbɒtəmɪst/", "t": "noun", "m": "A healthcare professional trained to draw blood from patients for clinical testing or transfusion.", "e": "The gentle phlebotomist found the vein painlessly on the very first try.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Pulmonology", "p": "/ˌpʌlməˈnɒlədʒi/", "t": "noun", "m": "A medical specialty that deals with diseases involving the respiratory tract.", "e": "Chronic asthma patients frequently consult specialists in pulmonology.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Nephrology", "p": "/nɛˈfrɒlədʒi/", "t": "noun", "m": "The branch of medicine that deals with the physiology and diseases of the kidneys.", "e": "The nephrology clinic specializes in managing chronic renal filtration disorders.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Gastroenterology", "p": "/ˌɡæstroʊˌɛntəˈrɒlədʒi/", "t": "noun", "m": "The branch of medicine focused on the digestive system and its disorders.", "e": "He consulted gastroenterology to identify food intolerances affecting his stomach.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Endocrinology", "p": "/ˌɛndoʊkrɪˈnɒlədʒi/", "t": "noun", "m": "The branch of physiology and medicine concerned with endocrine glands and hormones.", "e": "Her thyroid hormone levels were monitored closely by the endocrinology team.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Immunologist", "p": "/ˌɪmjʊˈnɒlədʒɪst/", "t": "noun", "m": "A specialist who treats disorders of the immune system like severe allergies or autoimmune illnesses.", "e": "The immunologist designed a personalized allergen desensitization therapy plan.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Anesthesiologist", "p": "/ˌænəsˌθiːziˈɒlədʒɪst/", "t": "noun", "m": "A medical doctor who specializes in anesthetics and pain management before, during, and after surgery.", "e": "The anesthesiologist monitored the patient's heart rate and oxygen levels throughout surgery.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Cardiothoracic", "p": "/ˌkɑːrdioʊθəˈræsɪk/", "t": "adjective", "m": "Relating to the surgical treatment of organs inside the thorax (the heart and lungs).", "e": "The cardiothoracic team performed a double valve replacement surgery.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Orthotist", "p": "/ˈɔːrθətɪst/", "t": "noun", "m": "A person who designs and fits braces and splints for people who need added support.", "e": "The pediatric orthotist measured the child for custom supportive foot arches.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Optometrist", "p": "/ɒpˈtɒmɪtrɪst/", "t": "noun", "m": "A person skilled in testing for defects of vision in order to prescribe corrective lenses.", "e": "The optometrist verified that his eyesight had improved since last year.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Audiologist", "p": "/ˌɔːdiˈɒlədʒɪst/", "t": "noun", "m": "A healthcare professional who evaluates, diagnoses, and treats hearing and balance disorders.", "e": "The audiologist calibrated a discreet hearing aid for the retired teacher.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Chiropractor", "p": "/ˈkaɪərəʊˌpræktər/", "t": "noun", "m": "A practitioner of the system of complementary medicine based on the diagnosis and manipulative treatment of misalignments of the joints.", "e": "Visiting the licensed chiropractor helped relieve tension in his lower spine.", "c": "Doctor & Specialized", "d": "Easy"},
    {"w": "Podiatrist", "p": "/pəˈdaɪətrɪst/", "t": "noun", "m": "A medical professional trained to diagnose and treat disorders of the foot and lower leg.", "e": "The podiatrist treated the marathon runner's chronic plantar fasciitis.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Geriatrician", "p": "/ˌdʒɛriəˈtrɪʃən/", "t": "noun", "m": "A physician who specializes in the care of elderly people.", "e": "The geriatrician reviewed all prescriptions to prevent negative drug interactions in seniors.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Neonatologist", "p": "/ˌniːoʊneɪˈtɒlədʒɪst/", "t": "noun", "m": "A subspecialty of pediatrics that consists of the medical care of newborn infants, especially the ill or premature.", "e": "The neonatologist cared for premature infants in the intensive care incubator ward.", "c": "Doctor & Specialized", "d": "Intermediate"},
    {"w": "Perinatology", "p": "/ˌpɛrɪneɪˈtɒlədʒi/", "t": "noun", "m": "A subspecialty of obstetrics concerned with the care of the fetus and complicated high-risk pregnancy.", "e": "Consulting perinatology ensured maternal and fetal safety throughout the pregnancy.", "c": "Doctor & Specialized", "d": "Intermediate"}
]

for item in startup_bonus:
    if item['w'].lower() not in existing:
        words.append(item)
        existing.add(item['w'].lower())

for item in doctor_bonus:
    if item['w'].lower() not in existing:
        words.append(item)
        existing.add(item['w'].lower())

# Final category tally
cat_counts = {}
diff_counts = {}
for w in words:
    cat_counts[w['c']] = cat_counts.get(w['c'], 0) + 1
    diff_counts[w['d']] = diff_counts.get(w['d'], 0) + 1

print("\n=== FINAL UPDATED CATEGORY STATS ===")
for k, v in sorted(cat_counts.items()):
    print(f"  {k}: {v}")

print("\n=== FINAL UPDATED DIFFICULTY STATS ===")
for k, v in diff_counts.items():
    print(f"  {k}: {v}")

with open('app/src/main/assets/oxford_words.json', 'w', encoding='utf-8') as f:
    json.dump(words, f, separators=(',', ':'))

print(f"\nSaved {len(words)} total words to oxford_words.json!")
